### ISSUE TITLE
Not returning anything once image is sent to the bot

### ISSUE THREAD

**Issue by keithlowc** [caiopo/tesseract-bot#1]
Not sure if I'm using your code correctly. I set up my token and directory path, but it doesn't seem to be returning anything once the image is sent. Is there any specific command to make the bot parse the image? I tried creating a new (To test the method):

`
dispatcher.addTelegramCommandHandler('run', handler.message)
`
But it still doesn't output anything or returns any parsed info.

Sorry if this comes as a newbie question.
-Keith

**Comment by caiopo** [comment]
That's strange, can you please attach a log of the bot starting and (trying to) respond to a message?

Thanks

**Comment by keithlowc** [comment]
018-05-17 00:14:34,818 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x1030d7890>]
2018-05-17 00:14:34,819 - telegram.bot - DEBUG - Exiting: getUpdates
2018-05-17 00:14:34,819 - telegram.bot - DEBUG - Entering: getUpdates
2018-05-17 00:14:34,819 - telegram.dispatcher - ERROR - An uncaught error was raised while processing an update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/telegram/dispatcher.py", line 180, in start
    self.processUpdate(update)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/telegram/dispatcher.py", line 248, in processUpdate
    self.dispatchTelegramMessage(update)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/telegram/dispatcher.py", line 572, in dispatchTelegramMessage
    self.dispatchTo(self.telegram_message_handlers, update)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/telegram/dispatcher.py", line 596, in dispatchTo
    self.call_handler(handler, update, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/telegram/dispatcher.py", line 637, in call_handler
    handler(self.bot, update, **target_kwargs)
  File "/Users/keithlow/Desktop/tesseract-bot-master/src/handler.py", line 76, in message
    photosize = bot.getFile(update.message.photo[-1].file_id)
IndexError: list index out of range

So, I tested it again and it worked for a couple seconds and then this happened. Not sure if its because the bot isn't registering the images until it enters into "getUpdates status". Maybe the image gets lost in that small gap.

018-05-17 00:16:30,985 - telegram.bot - DEBUG - []
2018-05-17 00:16:30,985 - telegram.bot - DEBUG - Exiting: getUpdates
2018-05-17 00:16:30,985 - telegram.bot - DEBUG - Entering: getUpdates

**Comment by caiopo** [comment]
I'm not sure if it's related, but the bot was made with Python 3 in mind. Could you try running it on Python 3 to see if it works?

**Comment by keithlowc** [comment]
Having this error now... Tried running everything on a V-env as well. But getting the same error.

2018-05-17 00:33:59,935 - telegram.bot - DEBUG - Entering: getMe
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tesseract_bot.py", line 51, in <module>
    main()
  File "tesseract_bot.py", line 35, in main
    print(updater.bot.getMe())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/bot.py", line 127, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/bot.py", line 177, in getMe
    result = request.get(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/utils/request.py", line 67, in decorator
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/utils/request.py", line 99, in get
    result = urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

**Comment by caiopo** [comment]
Hmm, this seems like an issue on your certificates.

Please take a look at this: tensorflow/tensorflow#10779

**Comment by keithlowc** [comment]
2018-05-17 10:58:32,062 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x10c7aa438>]
2018-05-17 10:58:32,063 - telegram.bot - DEBUG - Exiting: getUpdates
2018-05-17 10:58:32,063 - telegram.bot - DEBUG - Entering: getUpdates
2018-05-17 10:58:32,064 - telegram.dispatcher - ERROR - An uncaught error was raised while processing an update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/dispatcher.py", line 180, in start
    self.processUpdate(update)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/dispatcher.py", line 248, in processUpdate
    self.dispatchTelegramMessage(update)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/dispatcher.py", line 572, in dispatchTelegramMessage
    self.dispatchTo(self.telegram_message_handlers, update)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/dispatcher.py", line 596, in dispatchTo
    self.call_handler(handler, update, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/dispatcher.py", line 637, in call_handler
    handler(self.bot, update, **target_kwargs)
  File "/Users/keithlow/Desktop/tesseract-bot-master/src/handler.py", line 76, in message
    photosize = bot.getFile(update.message.photo[-1].file_id)
**IndexError: list index out of range**

Still giving the same error. 

Ps: Thanks for the SSL fix.

**Comment by keithlowc** [comment]
Okay so i figured it out. The problem was that I was sending as a file instead of image. Lol... I guess that on desktop its kinda different than on the phone. Thanks for the help.

**Comment by caiopo** [comment]
You're welcome. :)
